import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { HeroHighlight } from "@/components/ui/HeroHighlight";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Aldiipratama || Portfolio",
  description: "Generated by create next app",
  creator: "aldiipratama",
  icons: "/favicon.io",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <HeroHighlight>
            <Header />
            {children}
            <Footer />
          </HeroHighlight>
        </ThemeProvider>
      </body>
    </html>
  );
}
